name: Auto Build

on:
  push:
    branches: [ "master" ]
    paths:
      - 'RimTrans.Builder/**'
      - 'RimTrans.Lite/**'
      - 'RimTrans.TemplateExporter/**'
      - 'RimTrans.Trans/**'
      - 'duduluu.MVVM/**'
      - '**/*.sln'
      - '**/*.csproj'
      - '.github/workflows/**'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: RimTrans.sln
      Output_Dir: Output/Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore dependencies
        run: msbuild ${{ env.Solution_Name }} /t:Restore /p:Configuration=Release /m

      - name: Build solution (Release)
        run: msbuild ${{ env.Solution_Name }} /t:Build /p:Configuration=Release /m

      - name: Run unit tests
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Publish framework-dependent
        run: |
          dotnet publish ${{ env.Solution_Name }} `
            -c Release `
            -r win-x64 `
            --self-contained false `
            -o ${{ env.Output_Dir }}/framework-dependent

      - name: Publish self-contained
        run: |
          dotnet publish ${{ env.Solution_Name }} `
            -c Release `
            -r win-x64 `
            --self-contained true `
            -o ${{ env.Output_Dir }}/self-contained

      - name: Zip framework-dependent
        run: |
          Compress-Archive `
            -Path ${{ env.Output_Dir }}/framework-dependent/* `
            -DestinationPath ${{ env.Output_Dir }}/RimTrans-framework-dependent-win-x64.zip

      - name: Zip self-contained
        run: |
          Compress-Archive `
            -Path ${{ env.Output_Dir }}/self-contained/* `
            -DestinationPath ${{ env.Output_Dir }}/RimTrans-self-contained-win-x64.zip

      # ——— Upload artifacts ———
      - name: Upload framework-dependent
        uses: actions/upload-artifact@v4
        with:
          name: RimTrans-framework-dependent-win-x64
          path: ${{ env.Output_Dir }}/RimTrans-framework-dependent-win-x64.zip

      - name: Upload self-contained
        uses: actions/upload-artifact@v4
        with:
          name: RimTrans-self-contained-win-x64
          path: ${{ env.Output_Dir }}/RimTrans-self-contained-win-x64.zip
